theme = "catppuccin_macchiato"

##### Any Comments here are for desktop versions of helix and are intended for use with the MAIN git branch

[editor]
line-number = "relative"
bufferline = "multiple"
mouse = true
completion-replace = true
trim-trailing-whitespace = true
end-of-line-diagnostics = "hint"
# rainbow-brackets = true
color-modes = true
true-color = true
auto-info = true
cursorline = true
undercurl = true
clipboard-provider = "tmux"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "|"
skip-levels = 0

[editor.inline-diagnostics]
other-lines = "warning"
cursor-line = "disable"

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 30000

[editor.statusline]
left = ["mode", "spacer","spinner", "spacer", "diagnostics", "file-modification-indicator"]
center = ["file-name", "spacer", "file-encoding"]
right = ["version-control", "spacer", "spacer", "position", "total-line-numbers", "position-percentage", "spacer"]
separator = "â”‚"
mode.normal = "N"
mode.insert = "I"
mode.select = "S"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[keys.select]
0 = "goto_line_start"
"$" = "goto_line_end"
"^"= "goto_first_nonwhitespace"
G = "goto_file_end"
j = ["extend_line_down", "extend_to_line_bounds"]
k = ["extend_line_up", "extend_to_line_bounds"]

[keys.insert]
j = {k = "normal_mode"}


[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
- = "file_explorer"
e = "file_picker"
S-h = ":bprev"
S-l = ":bnext"
0 = "goto_line_start"
G = "goto_file_end"
V = ["select_mode", "extend_to_line_bounds"]
x = ["select_mode", "extend_to_line_bounds"]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]

[keys.normal.space.C]
r = ":config-reload"
o = ":config-open"

[keys.normal.space]
d = ":yank-diagnostic"
t = "diagnostics_picker"
f = "buffer_picker"
F = "no_op"
space = "file_picker_in_current_directory"
l = "global_search"

[keys.normal.space.b]
d = ":buffer-close"
D = ":buffer-close!"
o = ":buffer-close-others"
w = ":write"
Q = ":quit!"
q = ":quit"
l = ":toggle lsp.display-inlay-hints"

[keys.normal.space.s]
v = ":vsplit-new"
h = ":hsplit-new"
