"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# Default base colors with squared bottomline
[status]
overall = { fg = "#ffffff" }
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
perm_type = { fg = "magenta" }
perm_read = { fg = "yellow" }
perm_write = { fg = "red" }
perm_exec = { fg = "green" }
perm_sep = { fg = "darkgray" }

[mode]
normal_main = { fg = "white", bg = "blue", bold = true }
normal_alt = { fg = "gray" }
select_main = { fg = "white", bg = "red", bold = true }
select_alt = { fg = "gray" }
unset_main = { fg = "white", bg = "yellow", bold = true }
unset_alt = { fg = "gray" }

[which]
cols = 2
mask = { bg = "black" }
cand = { fg = "green" }
rest = { fg = "darkgray" }
desc = { fg = "magenta" }
separator = " "
separator_style = { fg = "darkgray" }

[confirm]
title = { fg = "white" }
content = { fg = "gray" }
list = { fg = "gray" }
btn_yes = { fg = "white", bg = "green" }
btn_no = { fg = "white", bg = "red" }
btn_labels = [ " Yes ", " No " ]

[spot]
title = { fg = "white" }
tbl_col = { fg = "green" }
tbl_cell = { fg = "white", bg = "blue" }

[notify]
title_info = { fg = "green" }
title_warn = { fg = "yellow" }
title_error = { fg = "red" }

[pick]
active = { fg = "green", bold = true }
inactive = { fg = "gray" }

[input]
title = { fg = "white" }
value = { fg = "gray" }
selected = { fg = "white", bg = "blue" }

[cmp]
active = { fg = "white", bg = "blue" }
inactive = { fg = "gray" }

[tasks]
title = { fg = "white" }
hovered = { fg = "green", underline = false }

[help]
on = { fg = "green" }
run = { fg = "magenta" }
desc = { fg = "gray" }
hovered = { fg = "white", bg = "blue", bold = true }
footer = { fg = "darkgray", bg = "black" }
